version: "3.8"

services:
  postgres:
    container_name: todo_postgres
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - endeavour_net

  backend:
    container_name: todo_backend
    build: .
    command: node server.js
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: postgres # matches postgres service name
      POSTGRES_PORT: 5432
    networks:
      - endeavour_net

volumes:
  postgres_data:

networks:
  endeavour_net:
