version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: todo_postgres
    environment:
      POSTGRES_USER: wyz
      POSTGRES_PASSWORD: wyz@123
      POSTGRES_DB: todo_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
